app/models.py
from flask_sqlalchemy import SQLAlchemy

from flask_login import LoginManager, UserMixin

from datetime import datetime, timezone
from werkzeug.security import generate_password_hash
from uuid import uuid4

db = SQLAlchemy()

login = LoginManager()

@login.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key=True)
    username = db.Column(db.String(15), nullable=False, unique=True)
    email = db.Column(db.String(150), nullable=False, unique=True)
    first_name = db.Column(db.String(100), nullable=True, default='')
    last_name = db.Column(db.String(100), nullable=True, default='')
    password = db.Column(db.String(150), nullable=False)
    created_on = db.Column(db.DateTime, nullable=False, default=datetime.now(timezone.utc))

    def __init__(self, username, email, password, first_name='', last_name=''):
        self.username = username
        self.email = email
        self.first_name = first_name
        self.last_name = last_name
        self.password = generate_password_hash(password) 
        self.id = str(uuid4())

class Player(db.Model):
    id = db.Column(db.String, primary_key=True)
    number = db.Column(db.Integer)
    first_name = db.Column(db.String(150), nullable=False) 
    last_name = db.Column(db.String(150), nullable=True) 
    position = db.Column(db.String(15))
    team = db.Column(db.String(150), nullable=False, default='Free Transfer')
    nationality = db.Column(db.String(150))
    transfer_cost = db.Column(db.String(150), nullable=False, default='$0m')

    def to_dict(self):
        return {
            'id': self.id,
            'number': self.number,
            'first_name': self.first_name,
            'last_name': self.last_name,
            'postion': self.position,
            'team': self.team,
            'nationality': self.nationality,
            'transfer_cost': self.transfer_cost
            }

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo


class signupForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    submit = SubmitField()


class signinForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField()

class updateUsernameForm(FlaskForm):
    newusername = StringField('New Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Change Username') 

app/__init__.py
from flask import Flask
from config import Config

from .api.routes import api
from .auth.routes import auth

from .models import db, login
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_object(Config)

app.register_blueprint(api)
app.register_blueprint(auth)

db.init_app(app)
migrate = Migrate(app, db)

login.init_app(app)
login.login_view = 'auth.signin'
login.login_message = 'Please sign in to see this page.'
login.login_message_category = 'danger'

from . import routes

from . import models

app/api/routes.py
from flask import Blueprint, jsonify
from app.models import Player

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/')
def test():
    return {'datadatadata': 'ooh look at this fancy data'}

@api.route('/players', methods=['GET'])
def players():
    """
    [GET] returns json data on all of the players in our database
    """
    players = [player.to_dict() for player in Player.query.all()]
    return jsonify(players)

@api.route('/player/<int:num>', methods=['GET'])
def get_number(num):
    '''
    [GET] /api/player/<int:num>
    returns all players with that number
    or None if no playes have that number
    '''
    players = Player.query.filter_by(number=num).all()
    if not players:
        return jsonify({num: None})
    return jsonify([x.to_dict() for x in players])

@api.route('/<string:tm>', methods=['GET'])
def get_team(tm):
    """
    [GET] /api/Manchester_City
    returns all players on the applicable team
    """
    tm = tm.replace('_', ' ')
    players = Player.query.filter_by(team=tm).all()
    if not players:
        return jsonify({tm: None})
    return jsonify([x.to_dict() for x in players])

app/routes.py
from app import app
from flask import render_template
from flask_login import login_required

@app.route('/')
def home():
    import requests as r
    data = r.get('https://pokeapi.co/api/v2/pokedex/hoenn')
    if data.status_code == 200:
        data = data.json()
        context={
            'name': data['name'].title(),
            'poke': data['pokemon_entries']
        }
    return render_template('index.html', **context)

@app.route('/about')
@login_required
def about():
    context = {
        'teacher': 'Sam',
        'students': ['Zaki', 'Vanessa', 'Paul', 'Shaharima', 'Mohammed', 'Ezekiel', 'Adrian', 'Ethan']
    }
    return render_template('about.html', classname='Foxes78', **context)

app/templates/about.html
{% extends 'components/layout.html' %}

{% block title %}About{% endblock %}

{% block content %}
<h5>Welcome to the about page. This is a Flask API being made by the {{ classname }} class!</h5>
<h5>The instructor for this class is {{ teacher }}.</h5>

{% for person in students %}
<p>Next student:</p>
<p>{{ person }}</p>
{% endfor %}

{% endblock content %}

app/templates/components/layout.html
<!doctype html>
<html lang="en">

<head>
    <title>Foxes78 API | {% block title %}{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/css/main.css">
</head>

<body>
    <nav class="nav nav-pills nav-fill">
        <a class="nav-link" href="{{ url_for('home') }}">Home</a>
        <a class="nav-link" href="{{ url_for('about') }}">About</a>
        <a class="nav-link" href="{{ url_for('api.test') }}">API Test Endpoint</a>
        {% if current_user.is_authenticated %}
            <a class="nav-link" href="{{ url_for('auth.profile') }}">Profile</a>
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
        {% else %}
            <a class="nav-link" href="{{ url_for('auth.signin') }}">Login</a>
            <a class="nav-link" href="{{ url_for('auth.signup') }}">Create an account</a>
        {% endif %}
    </nav>
    <div class="container-fluid">
        <div class="row justify-content-center">
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category, message in messages %}

                        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        {% block content %}

        {% endblock content %}
    </div>
    <!-- Optional JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/index.html
{% extends 'components/layout.html' %}

{% block title %}Homepage{% endblock title %}

{% block content %}
<h1>This page currently shows some data from an api call to the PokeAPI</h1>
<h5>Current region: {{ name }}</h5>

{% for pokemon in poke %}
    <h5>Name: {{ pokemon['pokemon_species']['name'] }}</h5>
    <p>    API URL: {{ pokemon['pokemon_species']['url'] }}</p>
{% endfor %}

{% endblock content %}